// @ts-nocheck
// Значения здесь — обычный CSS (шорткаты padding и border, var(--…) в background,
// zIndex строкой), а типы $mol_style_properties принимают только структурные
// формы, поэтому проверка типов для файла отключена.
namespace $.$$ {

	$mol_style_define( $piterjs_landing_cfp, {
		position: 'fixed',
		top: '0',
		left: '0',
		width: '100vw',
		height: '100vh',
		background: 'rgba(0, 0, 0, 0.85)',
		backdropFilter: 'blur(8px)',
		zIndex: '1000',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		padding: '20px',
		Cfp_modal_box: {
			background: '#111111',
			border: '1px solid #333333',
			borderRadius: '9px',
			maxWidth: '580px',
			width: '100%',
			maxHeight: '90vh',
			overflowY: 'auto',
			padding: '32px',
			display: 'flex',
			flexDirection: 'column',
			gap: '20px',
			boxShadow: '0 20px 60px rgba(0, 0, 0, 0.8)',
		},
		Cfp_header: {
			display: 'flex',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		Cfp_header_title: {
			fontFamily: 'var(--font-mono)',
			fontSize: '16px',
			fontWeight: '700',
			color: 'var(--color-caution-yellow)',
		},
		Cfp_close_btn: $piterjs_landing_style.close_btn,
		Cfp_desc: {
			fontSize: '14px',
			color: '#aaaaaa',
			lineHeight: '1.4',
		},
		Cfp_form: {
			display: 'flex',
			flexDirection: 'column',
			gap: '16px',
			width: '100%',
			$mol_textarea: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				minHeight: '120px',
				width: '100%',
				boxSizing: 'border-box',
				fontFamily: 'inherit',
				fontSize: '14px',
				lineHeight: '1.5',
				padding: '0',
				position: 'relative',
				overflow: 'hidden',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
			$mol_textarea_edit: {
				position: 'absolute',
				top: '0',
				left: '0',
				width: '100%',
				height: '100%',
				background: 'transparent',
				border: 'none',
				color: 'transparent',
				caretColor: '#fff313',
				padding: '10px 14px',
				margin: '0',
				fontFamily: 'inherit',
				fontSize: '14px',
				lineHeight: '1.5',
				boxSizing: 'border-box',
				boxShadow: 'none',
				outline: 'none',
				zIndex: '2',
			},
			$mol_textarea_view: {
				background: 'transparent',
				padding: '0',
				margin: '0',
				fontFamily: 'inherit',
				fontSize: '14px',
				lineHeight: '1.5',
				minHeight: '120px',
				width: '100%',
				boxSizing: 'border-box',
				zIndex: '1',
				display: 'block',
				$mol_text_code_rows: {
					padding: '10px 14px',
					margin: '0',
					fontFamily: 'inherit',
					fontSize: '14px',
					lineHeight: '1.5',
					color: '#ffffff',
					boxSizing: 'border-box',
				},
				$mol_button_copy: {
					display: 'none',
				},
			},
		},
		Cfp_field_email: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_contact: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_name: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_company: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_title: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
			$mol_string: {
				background: '#1a1a1a',
				border: '1px solid #333333',
				borderRadius: '6px',
				color: '#ffffff',
				padding: '10px 14px',
				fontSize: '14px',
				width: '100%',
				boxSizing: 'border-box',
				':focus-within': {
					borderColor: 'var(--color-caution-yellow)',
					boxShadow: '0 0 8px rgba(255, 243, 19, 0.2)',
				},
			},
		},
		Cfp_field_desc: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'stretch',
			gap: '6px',
			width: '100%',
		},
		Cfp_label_email: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_contact: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_name: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_company: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_title: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_label_desc: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '600',
			color: '#bbbbbb',
			marginBottom: '2px',
			display: 'block',
		},
		Cfp_submit_btn: {
			textTransform: 'uppercase',
			background: 'var(--color-caution-yellow)',
			color: '#000000',
			fontFamily: 'var(--font-mono)',
			fontWeight: '700',
			fontSize: '13px',
			padding: '12px',
			borderRadius: '6px',
			border: 'none',
			cursor: 'pointer',
			marginTop: '10px',
			width: '100%',
			justifyContent: 'center',
		},
	} )

}
