// @ts-nocheck
// Значения здесь — обычный CSS (шорткаты padding и border, var(--…) в background,
// zIndex строкой), а типы $mol_style_properties принимают только структурные
// формы, поэтому проверка типов для файла отключена.
namespace $.$$ {

	$mol_style_define( $piterjs_landing_footer, {
		backgroundColor: '#000000',
		borderTop: '1px solid #222222',
		padding: '32px 36px',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		boxSizing: 'border-box',
		Footer_inner: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			flexDirection: 'column',
			gap: '16px',
		},
		Footer_content: {
			width: '100%',
			display: 'flex',
			justifyContent: 'space-between',
			alignItems: 'center',
			flexWrap: 'wrap',
			gap: '20px',
		},
		Footer_copy: {
			display: 'flex',
			alignItems: 'center',
			gap: '12px',
		},
		Footer_logo: {
			width: '24px',
			height: '24px',
			borderRadius: '4px',
		},
		Footer_text: {
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			color: '#777777',
		},
		Footer_bottom: {
			display: 'flex',
			alignItems: 'center',
			gap: '6px',
			paddingTop: '0',
			borderTop: 'none',
		},
		Footer_author_prefix: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			color: '#555555',
			letterSpacing: '0.5px',
		},
		Footer_author: {
			background: 'transparent',
			backgroundColor: 'transparent',
			padding: '0',
			margin: '0',
			border: 'none',
			boxShadow: 'none',
			outline: 'none',
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			color: '#777777',
			textDecoration: 'none',
			textTransform: 'uppercase',
			letterSpacing: '0.5px',
			transition: 'color 0.15s ease',
			display: 'inline-block',
			height: 'auto',
			minHeight: '0',
			lineHeight: '1',
			':hover': {
				background: 'transparent',
				backgroundColor: 'transparent',
				color: 'var(--color-caution-yellow)',
				textDecoration: 'underline',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
			':focus': {
				background: 'transparent',
				backgroundColor: 'transparent',
				color: 'var(--color-caution-yellow)',
				textDecoration: 'underline',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
			':active': {
				background: 'transparent',
				backgroundColor: 'transparent',
				color: 'var(--color-caution-yellow)',
				textDecoration: 'underline',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
		},
		Footer_links: {
			display: 'flex',
			alignItems: 'center',
			gap: '16px',
		},
		Soc: {
			background: 'transparent',
			backgroundColor: 'transparent',
			padding: '0',
			margin: '0',
			border: 'none',
			boxShadow: 'none',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'center',
			opacity: '0.6',
			transition: 'opacity 0.15s ease',
			cursor: 'pointer',
			':hover': {
				background: 'transparent',
				backgroundColor: 'transparent',
				opacity: '1',
			},
		},
		Soc_icon: {
			width: '22px',
			height: '22px',
			objectFit: 'contain',
			display: 'block',
			background: 'transparent',
			backgroundColor: 'transparent',
		},
		'@media': {
			'(max-width: 992px)': {
				Footer_inner: {
					flexDirection: 'column',
					gap: '16px',
					textAlign: 'center',
					justifyContent: 'center',
				},
				Footer_copy: {
					flexDirection: 'column',
					gap: '12px',
				},
			},
			'(max-width: 600px)': {
				padding: '32px 12px',
			},
			'(max-width: 480px)': {
				padding: '24px 10px',
			},
		},
	} )

}
