// @ts-nocheck
// Значения здесь — обычный CSS (шорткаты padding и border, var(--…) в background,
// zIndex строкой), а типы $mol_style_properties принимают только структурные
// формы, поэтому проверка типов для файла отключена.
namespace $.$$ {

	$mol_style_define( $piterjs_landing_schedule, {
		backgroundColor: 'var(--color-industrial-white)',
		color: '#000000',
		padding: '90px 32px',
		display: 'flex',
		justifyContent: 'center',
		Schedule_content: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			flexDirection: 'column',
			gap: '36px',
		},
		Schedule_heading: {
			fontSize: 'clamp(28px, 4vw, 44px)',
			fontWeight: '300',
			letterSpacing: '-0.04em',
			color: '#000000',
			textTransform: 'uppercase',
		},
		Schedule_intro: {
			fontSize: '18px',
			color: '#4b4b4b',
			maxWidth: '800px',
			lineHeight: '1.5',
			marginTop: '-16px',
		},
		Talks_grid: {
			display: 'grid',
			gridTemplateColumns: '1fr 1fr',
			gap: '24px',
		},
		Talk: {
			background: '#ffffff',
			border: '1px solid #dcdcdc',
			borderRadius: '9px',
			padding: '28px',
			display: 'flex',
			flexDirection: 'column',
			gap: '16px',
			transition: 'border-color 0.15s ease, background-color 0.15s ease',
			':hover': {
				borderColor: '#000000',
				backgroundColor: '#fcfcfc',
			},
		},
		Talk_top: {
			display: 'flex',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		Talk_tag: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			background: '#000000',
			color: 'var(--color-caution-yellow)',
			padding: '4px 10px',
			borderRadius: '4px',
		},
		Talk_time: {
			fontFamily: 'var(--font-mono)',
			fontSize: '13px',
			fontWeight: '600',
			color: '#666666',
		},
		Talk_title: {
			fontSize: '20px',
			fontWeight: '600',
			color: '#000000',
			lineHeight: '1.35',
		},
		Talk_abstract: {
			fontSize: '14px',
			color: '#555555',
			lineHeight: '1.5',
			overflow: 'hidden',
			transition: 'max-height 0.35s cubic-bezier(0.16, 1, 0.3, 1)',
			// сам клип в 6 строк — в landing.view.css: -webkit-line-clamp
			// через $mol_style_define не выразить, см. комментарий там
		},
		Talk_more: {
			textTransform: 'uppercase',
			alignSelf: 'flex-start',
			background: 'transparent',
			border: 'none',
			boxShadow: 'none',
			padding: '0',
			marginTop: '-8px',
			color: '#000000',
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			cursor: 'pointer',
			textDecoration: 'underline',
			transition: 'color 0.15s ease',
			':hover': {
				background: 'transparent',
				boxShadow: 'none',
				color: '#666666',
			},
		},
		Talk_speaker: {
			display: 'flex',
			flexDirection: 'row',
			alignItems: 'flex-start',
			gap: '14px',
			marginTop: 'auto',
			paddingTop: '16px',
			borderTop: '1px solid #eeeeee',
		},
		Speaker_photo: {
			width: '52px',
			height: '52px',
			borderRadius: '50%',
			objectFit: 'cover',
			border: '2px solid var(--color-caution-yellow)',
			flexShrink: '0',
		},
		Speaker_info: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'flex-start',
			gap: '4px',
			flex: '1 1 auto',
			minWidth: '0',
		},
		Speaker_name: {
			fontWeight: '600',
			fontSize: '15px',
			color: '#000000',
			display: 'block',
			lineHeight: '1.3',
		},
		Speaker_role: {
			fontSize: '12px',
			color: '#666666',
			fontFamily: 'var(--font-mono)',
			display: 'block',
			whiteSpace: 'normal',
			wordBreak: 'break-word',
			lineHeight: '1.45',
			width: '100%',
		},
		Cfp_cta_card: {
			background: '#000000',
			color: '#ffffff',
			borderRadius: '9px',
			padding: '32px',
			display: 'flex',
			flexDirection: 'column',
			gap: '14px',
		},
		Cfp_cta_badge: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			color: 'var(--color-caution-yellow)',
			letterSpacing: '1px',
		},
		Cfp_cta_title: {
			fontSize: '22px',
			fontWeight: '400',
			letterSpacing: '-0.02em',
		},
		Cfp_cta_text: {
			fontSize: '15px',
			color: '#afafaf',
			lineHeight: '1.5',
			maxWidth: '800px',
		},
		Cfp_open_btn: {
			... $piterjs_landing_style.cfp_btn,
			alignSelf: 'flex-start',
			marginTop: '8px',
		},
		Venue_card: {
			background: '#ffffff',
			border: '1px solid #dcdcdc',
			borderRadius: '9px',
			padding: '28px',
			display: 'flex',
			flexDirection: 'column',
			gap: '8px',
		},
		Venue_badge: {
			fontFamily: 'var(--font-mono)',
			fontSize: '11px',
			fontWeight: '700',
			color: '#777777',
		},
		Venue_title: {
			fontSize: '22px',
			fontWeight: '600',
			color: '#000000',
		},
		Venue_meta1: {
			fontSize: '14px',
			color: '#444444',
		},
		Venue_meta2: {
			fontSize: '14px',
			color: '#444444',
		},
		Venue_meta3: {
			fontSize: '14px',
			color: '#444444',
		},
		Venue_map_btn: {
			textTransform: 'uppercase',
			alignSelf: 'flex-start',
			display: 'inline-flex',
			width: 'auto',
			color: '#000000',
			fontFamily: 'var(--font-mono)',
			fontWeight: '600',
			fontSize: '13px',
			marginTop: '8px',
			textDecoration: 'underline',
			background: 'transparent',
			backgroundColor: 'transparent',
			padding: '0',
			':hover': {
				color: '#000000',
				background: 'transparent',
				backgroundColor: 'transparent',
				textDecoration: 'none',
			},
		},
		'@media': {
			'(max-width: 992px)': {
				Talks_grid: {
					gridTemplateColumns: '1fr',
				},
				Cfp_cta_card: {
					flexDirection: 'column',
					gap: '24px',
					textAlign: 'center',
					alignItems: 'center',
				},
				Cfp_open_btn: {
					alignSelf: 'center',
				},
			},
			'(max-width: 600px)': {
				padding: '48px 12px',
				Venue_card: {
					padding: '20px 16px',
				},
				Cfp_cta_card: {
					padding: '24px 16px',
				},
				Talks_grid: {
					gap: '20px',
				},
			},
			'(max-width: 480px)': {
				padding: '40px 10px',
			},
		},
	} )

}
