// @ts-nocheck
// Значения здесь — обычный CSS (шорткаты padding и border, var(--…) в background,
// zIndex строкой), а типы $mol_style_properties принимают только структурные
// формы, поэтому проверка типов для файла отключена.
namespace $.$$ {

	$mol_style_define( $piterjs_landing_header, {
		Header: {
			position: 'fixed',
			top: '0',
			left: '0',
			width: '100%',
			zIndex: '1000',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'center',
			padding: '16px 36px',
			backgroundColor: 'rgba(0, 0, 0, 0.85)',
			backdropFilter: 'blur(12px)',
			borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
			boxSizing: 'border-box',
		},
		Header_inner: {
			maxWidth: '1200px',
			width: '100%',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'space-between',
		},
		Logo_link: {
			display: 'flex',
			alignItems: 'center',
			gap: '10px',
			textDecoration: 'none',
			color: '#ffffff',
			paddingLeft: '0',
			marginLeft: '0',
			paddingTop: '0',
			paddingBottom: '0',
		},
		Logo_img: {
			width: '28px',
			height: '28px',
			borderRadius: '4px',
		},
		Logo_title: {
			fontFamily: 'var(--font-mono)',
			fontWeight: '700',
			fontSize: '16px',
			letterSpacing: '1px',
			color: '#ffffff',
		},
		Logo_tag: {
			fontFamily: 'var(--font-mono)',
			fontSize: '10px',
			padding: '2px 6px',
			backgroundColor: 'var(--color-caution-yellow)',
			color: '#000000',
			fontWeight: '700',
			borderRadius: '4px',
		},
		Nav: {
			display: 'flex',
			alignItems: 'center',
			gap: '8px',
			background: '#1a1a1a',
			padding: '4px 6px',
			borderRadius: '6px',
			border: '1px solid #333333',
			$mol_link: {
				padding: '6px 14px',
				fontSize: '13px',
				fontWeight: '500',
				color: '#afafaf',
				textDecoration: 'none',
				borderRadius: '4px',
				transition: 'all 0.2s ease',
				':hover': {
					color: '#ffffff',
					background: 'rgba(255, 255, 255, 0.08)',
				},
				'@': {
					piterjs_landing_nav_active: {
						true: {
							color: 'var(--color-caution-yellow)',
							background: 'rgba(255, 255, 255, 0.08)',
						},
					},
				},
			},
		},
		Nav_actions: {
			display: 'flex',
			alignItems: 'center',
			gap: '12px',
		},
		Back_link: {
			textTransform: 'uppercase',
			fontFamily: 'var(--font-mono)',
			fontSize: '12px',
			color: '#afafaf',
			textDecoration: 'none',
			padding: '8px 12px',
			border: '1px solid #333333',
			borderRadius: '6px',
			background: 'transparent',
			transition: 'color 0.15s ease, border-color 0.15s ease, background-color 0.15s ease',
			':hover': {
				color: '#fff313',
				borderColor: '#fff313',
				background: 'rgba(255, 243, 19, 0.08)',
			},
		},
		Rsvp_btn: {
			textTransform: 'uppercase',
			backgroundColor: 'var(--color-caution-yellow)',
			color: '#000000',
			fontFamily: 'var(--font-mono)',
			fontWeight: '700',
			fontSize: '13px',
			padding: '8px 16px',
			borderRadius: '6px',
			border: 'none',
			cursor: 'pointer',
			transition: 'background-color 0.15s ease',
			':hover': {
				backgroundColor: '#ffe600',
			},
		},
		Burger_btn: {
			display: 'none',
			width: '32px',
			height: '32px',
			minHeight: '32px',
			maxHeight: '32px',
			minWidth: '32px',
			maxWidth: '32px',
			padding: '0',
			background: 'transparent',
			backgroundColor: 'transparent',
			border: 'none',
			boxShadow: 'none',
			outline: 'none',
			cursor: 'pointer',
			position: 'relative',
			margin: '0',
			boxSizing: 'border-box',
			alignSelf: 'center',
			':hover': {
				background: 'transparent',
				backgroundColor: 'transparent',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
			':focus': {
				background: 'transparent',
				backgroundColor: 'transparent',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
			':active': {
				background: 'transparent',
				backgroundColor: 'transparent',
				boxShadow: 'none',
				border: 'none',
				outline: 'none',
			},
		},
		Burger_line1: {
			position: 'absolute',
			left: 'calc(50% - 12px)',
			width: '24px',
			height: '2px',
			borderRadius: '2px',
			backgroundColor: '#fff313',
			transition: 'top 0.25s ease, transform 0.25s ease, opacity 0.25s ease',
			transformOrigin: '50% 50%',
			boxSizing: 'border-box',
			top: 'calc(50% - 8px)',
			transform: 'none',
		},
		Burger_line2: {
			position: 'absolute',
			left: 'calc(50% - 12px)',
			width: '24px',
			height: '2px',
			borderRadius: '2px',
			backgroundColor: '#fff313',
			transition: 'top 0.25s ease, transform 0.25s ease, opacity 0.25s ease',
			transformOrigin: '50% 50%',
			boxSizing: 'border-box',
			top: 'calc(50% - 1px)',
			transform: 'none',
			opacity: '1',
		},
		Burger_line3: {
			position: 'absolute',
			left: 'calc(50% - 12px)',
			width: '24px',
			height: '2px',
			borderRadius: '2px',
			backgroundColor: '#fff313',
			transition: 'top 0.25s ease, transform 0.25s ease, opacity 0.25s ease',
			transformOrigin: '50% 50%',
			boxSizing: 'border-box',
			top: 'calc(50% + 6px)',
			transform: 'none',
		},
		Nav_mobile: {
			display: 'none',
		},
		'@': {
			piterjs_landing_menu_open: {
				true: {
					Burger_line1: {
						top: 'calc(50% - 1px)',
						transform: 'rotate(45deg)',
					},
					Burger_line2: {
						top: 'calc(50% - 1px)',
						opacity: '0',
						transform: 'scaleX(0)',
					},
					Burger_line3: {
						top: 'calc(50% - 1px)',
						transform: 'rotate(-45deg)',
					},
				},
			},
		},
		'@media': {
			'(max-width: 1200px)': {
				Back_link: {
					display: 'none',
				},
			},
			'(max-width: 992px)': {
				Burger_btn: {
					display: 'flex',
				},
				Nav: {
					display: 'none',
				},
				Header: {
					position: 'fixed',
					top: '0',
					left: '0',
					width: '100%',
					zIndex: '1000',
					backgroundColor: 'rgba(0, 0, 0, 0.95)',
					backdropFilter: 'blur(12px)',
				},
				Nav_mobile: {
					display: 'flex',
					position: 'fixed',
					top: '60px',
					left: '0',
					width: '100%',
					backgroundColor: '#161616',
					borderBottom: '1px solid #4b4b4b',
					flexDirection: 'column',
					padding: '20px',
					gap: '12px',
					borderRadius: '0 0 16px 16px',
					transform: 'translateY(-110%)',
					opacity: '0',
					pointerEvents: 'none',
					transition: 'transform 0.35s cubic-bezier(0.16, 1, 0.3, 1), opacity 0.25s ease',
					boxShadow: '0 16px 32px rgba(0, 0, 0, 0.8)',
					zIndex: '900',
					$mol_link: {
						textAlign: 'center',
						padding: '12px',
						fontSize: '16px',
						color: '#eeeeee',
						textDecoration: 'none',
						borderRadius: '8px',
						background: '#111111',
						border: '1px solid #2a2a2a',
						':hover': {
							color: '#fff313',
							background: '#222222',
						},
						'@': {
							piterjs_landing_nav_active: {
								true: {
									color: '#fff313',
									background: '#222222',
								},
							},
						},
					},
				},
				'@': {
					piterjs_landing_menu_open: {
						true: {
							Nav_mobile: {
								transform: 'translateY(0)',
								opacity: '1',
								pointerEvents: 'auto',
							},
						},
					},
				},
			},
			'(max-width: 768px)': {
				Header: {
					padding: '12px 16px',
				},
				Nav_actions: {
					gap: '8px',
				},
				Rsvp_btn: {
					padding: '6px 12px',
					height: '32px',
					minHeight: '32px',
					maxHeight: '32px',
					fontSize: '12px',
					display: 'inline-flex',
					alignItems: 'center',
					justifyContent: 'center',
					lineHeight: '1',
				},
			},
			'(max-width: 600px)': {
				Header: {
					padding: '10px 12px',
				},
				Back_link: {
					display: 'none',
				},
				Rsvp_btn: {
					padding: '6px 10px',
					height: '32px',
					minHeight: '32px',
					maxHeight: '32px',
					fontSize: '11px',
					display: 'inline-flex',
					alignItems: 'center',
					justifyContent: 'center',
					lineHeight: '1',
				},
			},
			'(max-width: 480px)': {
				Rsvp_btn: {
					display: 'none',
				},
			},
		},
	} )

}
